---
title: "Amortiguadores de masa sintonizados - Parte 1"
author: "Luis Damián García Vega, José de Jesús García Piña, Gabriel Peytral Borja"
date: "09/12/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newcommand{\bcenter}{\begin{center}}
\newcommand{\ecenter}{\end{center}}

\bcenter
# Proyecto final de Ecuaciones Diferenciales Ordinarias: 
# Amoritiguadores de masa sintonizados
\ecenter

## **Introducción**
Los amortiguadores de masa sintonizada son masas vibrantes que se mueven fuera de fase con el movimiento de alguna estructura en la que se está suspendida, generalmente se instalan en la parte superior de los edificios y que al estar en sintonía con la frecuencia de movimiento del edificio funcionan como un contrapeso que oscila y contrarresta el movimiento del edificio disipando la energía de un terremoto o del viento.  
Esta no es la única aplicación práctica que tienen, también pueden ser usados en mesas de cirugía para evitar el movimiento de estas durante una intervención quirurjica de alta precisión.   
La eficacia de disipación de energía de un TMD depende de la precisión de su sintonía, el tamaño de su masa en comparación con la masa modal de su modo objetivo, es decir, su relación de masa, y la extensión de la amortiguación interna incorporada en el amortiguador de masa sintonizado.  
Básicamente, uno puede pensar en un TMD como un contrapeso mecánico para una estructura que consta de una masa en movimiento (aproximadamente 1 a 2% de la masa de la estructura). 

**Modelado de un amortiguador de masa sintonizado**
Representamos la rigidez de la masa original de un sistema usando un resorte y la absorción de energía usando un amortiguador. Adjuntaremos un resorte y un amortiguador (TMD) a la masa original y exploraremos qué tanto se puede reducir las vibraciones debidas a fuerzas externas. Se caracterizará el desplazamiento de la masa sobre una posición de equilibrio inicial por un solo grado de libertad. Sin embargo, en el caso del TMD, agregaremos una segunda masa y un resorte a la masa primaria. El desplazamiento de la masa TMD se caracterizará por un grado separado de libertad sobre su propia posición de equilibrio inicial. Por lo tanto, un TMD es un par de osciladores armónicos amortiguados acoplados.  
Una gran masa $m_1$ en un "resorte" con constante de resorte $k_1$ se acopla a una masa más pequeña $m_2$ por un resorte con constante de resorte $k_2$ y un amortiguador con coeficiente de amortiguación $c_2$. La gran masa también podría estar naturalmente amortiguada con un coeficiente de amortiguación o de restauración $c_1$. Para nuestro estudio, tomamos $c_1 = 0$ y $c_2 = 0$. Es decir, supondremos que no hay resistencia ni amortiguamiento de la masa original o del TMD. Al ajustar los valores de $m_2$ y $k_2$ la amplitud máxima de las oscilaciones de $m_1$ se puede reducir.  
En este caso sin resistencia ($c_1 = 0$ y $c_2 = 0$) cuando aplicamos una carga externa o fuerza impulsora, $f(t)$, tenemos el siguiente modelo de ecuación diferencial de un solo grado de libertad para el desplazamiento, $y(t)$, de nuestra masa desde su equilibrio estático, es decir, un sistema de resorte-masa (sin salpicadero):
$$my''(t) + ky(t) = f(t), y(0)=y_0, y'(0) = v_0; (1)$$
La frecuencia natural de masa $m_1$ se puede obtener de la solución de la porción homogénea,(2), de nuestra ecuación diferencial (1),

$$my''(t) + ky(t) = 0, \ y(0)=y_0, \  y'(0) = v_0; \ (2)$$
De (3) vemos que la frecuencia natural de la solución no impulsada u homogénea de (2) es $\omega_0 = \sqrt \frac {k}{m}  $ mientras que la solución homogénea completa para (1) es:
$$y(t)= \frac {v_0 \sqrt m \sin(\sqrt \frac {k}{m}t)+y_0 \sqrt k \cos(\sqrt \frac {k}{m} t)}{\sqrt k}, \ (3) $$

### *Actividad 1*
Usando la Segunda Ley de Newton, que dice que la masa multiplicada por la aceleración de esa masa es igual a la suma de todas las fuerzas externas que actúan sobre la masa, y la Figura 4 como fuente del Diagrama de cuerpo libre,muestran que las ecuaciones que gobiernan los movimientos de la estructura y el amortiguador están dadas por:

$$ m_1 \space x''_1(t) = -k_1 x_1(t)- c_1x'_1(t)-k_2(x_1(t)-x_2(t))-c_2(x'_1(t)-x'_2(t))+p_0 \space cos(\omega t), \space\space\space\space (1)$$
$$ m_2 \space x''_2(t) = -k_2(x_2(t)-x_1(t))-c_2(x'_2(t)-x'_1(t)), \space\space\space\space (2) $$

### *Actividad 2*
a) Determine la forma de las ecuaciones de la actividad anterior cuando $c_1 = 0$ y $c_2 = 0$.
b) En el sistema resultante use $m_1 = 10$ y $k_1 = 90$ con $y(0) = 0$ y $y''(0) = 0$, mientras que $f(t) =10 \space\space \cos (3t)$ y establezca $m_2 = 1$ con $k_2 = 0$, es decir, retirando el segundo sistema de masas. Explique los resultados de importancia física e impacto de los números 10, 90 y 3 en la oracióna nterior en términos del movimiento del oscilador inicial.
c) Resuelva la ecuacion diferencia simple resultante para el movimiento de la masa $m_1$ durante un intervalo de tiempo de 20 unidades y grafique el desplazamiento de esa masa, $x_1(t)$, durante ese intervalo de tiempo. Explique las observaciones. 
d) En las ecuaciones de la actividad anterior use los valores $m_1=10$ y $k_1=90$ con $y(0)=0$ y $y'(0)=0$ mientras $f(t)=10 \space\space \cos (3t)$ y establezca $m_2=1$ con valores variables de $k_2$. Mantenga $c_1=0$ y $c_2=0$. ¿Qué observa en la amplitud máxima de la masa inicial $m_1$ cuando se cambia $k_2$? Defiende tu observación con datos y/o gráficas.
e) De (d) ¿cuál es el "mejor" valor de $k_2$? Asegúrese de definir la palabra "mejor".
f) Para obtener el mejor valor de $k_2$, determine el desplazamiento de amplitud máximo para la masa $m_1 ,\space\space x_1 (t)$en un rango de frecuencias  

### *Actividad 3*
Consideremos otra configuración comparable a la Actividad 2 para la práctica. Observe que la masa $m_2$ es solo el 1% de la masa $m_1$, lo cual es bastante realista en el diseño estructural cuando se utilizan TMD.
a) Determine la forma de las ecuaciones de la actividad anterior cuando $c_1 = 0$ y $c_2 = 0$
b) En el sistema resultante use $m_1 = 10$ y $k_1 = 90$ con $y(0) = 0$ y $y'(0) = 0$ mientras $f(t) =10 \space\space \cos (3t)$ y ajuste $m_2 = 0.1$ con $k_2 = 0$, es decir, retire el segundo sistema de masa. Explique la importancia física e impacto de los números 10, 90 y 3 en la oración anterior en términos del movimiento del oscilador inicial.
c) Resuelva la ecuación diferencial simple resultante para el movimiento de la masa $m_1$ durante un intervalo de tiempo de 20 unidades y grafique el desplazamiento de esa masa, $x_1 (t)$, durante ese intervalo de tiempo. Explique las observaciones.
d) En las ecuaciones de la actividad anterior use los valores $m_1=10$ y $k_1=90$ con $y(0)=0$ y $y'(0)=0$ mientras $f(t)=5 \space\space \cos (3t)$ y establezca $m_2=0.1$ con valores variables de $k_2$. Mantenga $c_1=0$ y $c_2=0$. ¿Qué observa en la amplitud máxima de la masa inicial $m_1$ cuando se cambia $k_2$? Defiende tu observación con datos y/o gráficas.
e) De (d) ¿cuál es el "mejor" valor de $k_2$? Asegúrese de definir la palabra "mejor".
f) Para obtener el mejor valor de $k_2$, determine el desplazamiento de amplitud máximo para la masa $m_1 ,\space\space x_1 (t)$en un rango de frecuencias  

### *Actividad 4*
Del material introductorio para este escenario ofrecido anteriormente y los análisis en las Actividades 2 y 3 realiza una descripción de cómo construir un TMD para detener los fenómenos de resonancia en el caso de las siguientes ecuaciones, que son el caso de las ecuaciones de la actividad 1 donde no hay amortiguamiento, es decir, $c_1 = 0$ y $c_2 = 0$:
$$ m_1 \space x''_1(t) = -k_1 x_1(t)-k_2(x_1(t)-x_2(t))+p_0 \space cos(\omega t), \space\space\space\space (1)$$
$$ m_2 \space x''_2(t) = -k_2(x_2(t)-x_1(t)), \space\space\space\space (2) $$